### ISSUE TITLE
这个image要玩坏樱花的样子了

### ISSUE THREAD

**Issue by Justsoos** [malaohu/squid-with-net-speeder#1]
随便去扫一下樱花的IP，凡是开着443端口，返回内容有squid 字样的，差不多都是这个 image作的 https 代理。在hub 上，有100k+ 的pull，相信很大部分在樱花上，**没有加任何密码认证机制的公开代理服务器**。
这样下去，整个网段被GFW封锁可能性非常大。

**Comment by Justsoos** [comment]
也许迟早都会被玩坏。担心也多余

**Comment by malaohu** [comment]
呃。Squid只有一层SSL加密。确实容易被GFW识别。
